name: AAT_env
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/simpleitk/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - box2d-py=2.3.8=py38h709712a_3
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - ffmpeg=4.3.2=hca11adc_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=pyhd8ed1ab_6
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gym-box2d=0.21.0=py38h578d9bd_2
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.9.0=11_linux64_openblas
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1k=h7f98852_0
  - python=3.8.0=h0371630_2
  - python_abi=3.8=2_cp38
  - readline=7.0=h7b6447c_5
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.11=h1ccaba5_0
  - x264=1!161.3030=h7f98852_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==1.3.0
    - aiosignal==1.3.1
    - ale-py==0.8.1
    - annotated-types==0.7.0
    - anyio==4.5.2
    - astunparse==1.6.3
    - atari-py==0.2.9
    - attrdict==2.0.1
    - attrs==23.1.0
    - autorom==0.4.2
    - autorom-accept-rom-license==0.4.2
    - cached-property==1.5.2
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - chex==0.1.7
    - click==8.1.3
    - cloudpickle==1.2.2
    - commonmark==0.9.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - cython==0.29.32
    - d4rl==1.1
    - decorator==5.1.1
    - distlib==0.3.6
    - distro==1.9.0
    - dm-control==1.0.8
    - dm-env==1.5
    - dm-tree==0.1.7
    - dopamine-rl==4.0.6
    - einops==0.6.0
    - etils==1.2.0
    - exceptiongroup==1.2.2
    - farama-notifications==0.0.4
    - fasteners==0.18
    - filelock==3.9.0
    - fire==0.4.0
    - flatbuffers==23.3.3
    - flax==0.6.9
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - gast==0.4.0
    - gfootball==2.10.2
    - gin-config==0.5.0
    - glcontext==2.3.7
    - glfw==1.12.0
    - google-ai-generativelanguage==0.1.0
    - google-api-core==2.24.2
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - google-generativeai==0.1.0rc1
    - google-pasta==0.2.0
    - googleapis-common-protos==1.69.2
    - gpytorch==1.12.dev3+gaeb5e237
    - grpcio==1.70.0
    - grpcio-status==1.63.0rc1
    - gtimer==1.0.0b5
    - gym==0.15.7
    - gym3==0.3.3
    - gymnasium==0.28.1
    - h11==0.14.0
    - h5py==3.7.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - idna==3.4
    - imageio==2.31.1
    - imageio-ffmpeg==0.3.0
    - importlib-metadata==4.13.0
    - importlib-resources==5.10.0
    - jax==0.4.8
    - jax-jumpy==1.0.0
    - jaxlib==0.4.7
    - jaxtyping==0.2.19
    - jiter==0.9.0
    - joblib==1.2.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - keras==2.12.0
    - kiwisolver==1.4.4
    - labmaze==1.0.5
    - lazy-loader==0.3
    - libclang==16.0.0
    - linear-operator==0.5.0
    - llvmlite==0.39.1
    - loguru==0.5.3
    - lxml==4.9.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - mjrl==1.0.0
    - ml-dtypes==0.1.0
    - moderngl==5.7.4
    - msgpack==1.0.5
    - mujoco==2.3.0
    - mujoco-py==2.1.2.14
    - mypy-extensions==0.4.3
    - nest-asyncio==1.5.6
    - networkx==3.0
    - numba==0.56.4
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - openai==1.66.5
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - optax==0.1.5
    - orbax-checkpoint==0.2.1
    - packaging==21.3
    - pandas==1.5.1
    - pillow==9.3.0
    - pip==25.0.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.5.0
    - procgen==0.10.7
    - proto-plus==1.26.1
    - protobuf==4.25.6
    - psutil==5.9.8
    - pulp==2.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==3.2.5
    - pycparser==2.21
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pygame==2.3.0
    - pyglet==1.5.0
    - pygments==2.13.0
    - pyopengl==3.1.6
    - pyparsing==2.4.7
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pywavelets==1.4.1
    - pyyaml==6.0
    - ray==2.4.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==12.6.0
    - rsa==4.9
    - scikit-image==0.21.0
    - scikit-learn==1.2.0
    - scipy==1.9.3
    - seaborn==0.12.2
    - setuptools==69.1.1
    - shimmy==0.2.1
    - six==1.16.0
    - sklearn==0.0.post1
    - sniffio==1.3.1
    - stable-baselines3==1.6.2
    - tabulate==0.9.0
    - tenacity==9.0.0
    - tensorboard==2.12.2
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - tensorflow-probability==0.19.0
    - tensorstore==0.1.36
    - termcolor==2.1.1
    - tf-slim==1.1.0
    - threadpoolctl==3.1.0
    - tianshou==0.4.2
    - tifffile==2023.7.10
    - toolz==0.12.0
    - torch==1.13.0
    - torchnet==0.0.4
    - torchvision==0.14.0
    - tornado==6.2
    - tqdm==4.64.1
    - typed-argument-parser==1.7.2
    - typeguard==2.13.3
    - typing-extensions==4.12.2
    - typing-inspect==0.8.0
    - urllib3==1.26.12
    - virtualenv==20.21.0
    - visdom==0.2.4
    - websocket-client==1.5.1
    - werkzeug==2.2.2
    - wheel==0.42.0
    - wrapt==1.14.1
    - zipp==3.10.0
prefix: /home/heshenghong/anaconda3/envs/AAT_env
